Repository team-vera6/career-client, pull requests merged in 2024-09, with the labels that each got.

#59 [FEAT] 회고 api 1차 작업
  src/apis/projects/delete.ts
  src/apis/projects/get.ts
  src/apis/review/get.ts
  src/apis/review/post.ts
  src/apis/todos/delete.ts
  src/apis/todos/post.ts
  src/app/review/_components/week-info/WeekInfo.tsx
  src/app/review/_components/weekly-memo/WeeklyMemo.tsx
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/step1/_components/paging-button/PagingButton.tsx
  src/app/review/step1/_components/todo/TodoList.tsx
  src/app/review/step1/page.tsx
  src/app/review/stores.ts
  src/types/project.ts
  src/utils/date.ts
Labels: 공통, 회고

#62 [FEAT] 사용자 토큰 만료, getCurrentWeek, 하이라이트/로우라이트 타입 수정
  src/app/(with-navigation)/dashboards/page.tsx
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/step1/_components/todo/TodoList.tsx
  src/app/review/stores.ts
  src/app/review/types.ts
  src/hooks/useUser.tsx
  src/utils/date.ts
Labels: 공통, 대시보드

#63 [FIX] 프로젝트 api 연동
  src/apis/projects/get.ts
  src/components/action-sheets/create-project/CreateProjectSheet.tsx
  src/components/action-sheets/project-detail/ProjectDetailSheet.tsx
Labels: 프로젝트

#64 [FIX] 히스토리 페이지 수정
  src/apis/memo/get.ts
  src/apis/reports/get.ts
  src/app/(with-navigation)/history/_components/Category.tsx
  src/app/(with-navigation)/history/memo/_components/MemoHistory/MemoHistory.tsx
  src/app/(with-navigation)/history/memo/_components/MemoHistory/MemoWeekGroup.tsx
  src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetail.tsx
  src/components/toggle-switch/ToggleSwitch.tsx
  src/stores/bookmark/showOnlyBookmarkAtom.ts
Labels: 히스토리

#67 [FEAT] 주차 이동 구현
  src/app/(with-navigation)/dashboards/_components/MemoList.tsx
  src/app/(with-navigation)/dashboards/_components/TodoList.tsx
  src/app/(with-navigation)/dashboards/_components/WeekNavigator.tsx
  src/app/(with-navigation)/dashboards/page.tsx
  src/components/header/Header.tsx
  src/components/header/WeekInfo.tsx
  src/stores/week/displayWeek.ts
Labels: 공통, 대시보드

#66 [FEAT] 회고 api 개발 완료
  .gitignore
  src/apis/index.ts
  src/apis/projects/get.ts
  src/apis/review/delete.ts
  src/apis/review/get.ts
  src/apis/review/patch.ts
  src/apis/review/post.ts
  src/apis/review/put.ts
  src/apis/todos/post.ts
  src/apis/todos/put.ts
  src/app/review/_components/add-button/AddButton.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewContainer.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewItem.tsx
  src/app/review/_components/delete-button/DeleteButton.tsx
  src/app/review/_components/last-week-review/LastWeekReviewContainer.tsx
  src/app/review/_components/last-week-review/LastWeekReviewItem.tsx
  src/app/review/dummy.ts
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/step1/_components/paging-button/PagingButton.tsx
  src/app/review/step1/_components/todo/ListItem.tsx
  src/app/review/step1/_components/todo/TodoList.tsx
  src/app/review/step2/_components/paging-button/PagingButton.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/app/review/stores.ts
  src/app/review/types.ts
  src/components/dropdown/Dropdown.tsx
  src/hooks/useReviewsApi.tsx
  src/hooks/useTodosApi.tsx
  src/utils/number.ts
Labels: 공통, 회고

#68 [FIX] 히스토리 페이지 api 리턴 타입 수정
  src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetail.tsx
  src/app/review/_components/last-week-review/LastWeekReviewItem.tsx
  src/types/highlight.ts
Labels: 히스토리

#69 [FIX] dropdown 스토리 파일 타입 수정
  src/components/dropdown/Dropdown.stories.tsx
Labels: 공통

#71 [FEAT] 회고 애니메이션 적용, 코멘트 반영
  src/apis/review/patch.ts
  src/app/(with-navigation)/dashboards/page.tsx
  src/app/(with-navigation)/page.tsx
  src/app/review/_components/delete-button/DeleteButton.tsx
  src/app/review/_components/week-info/ActivePage.tsx
  src/app/review/dummy.ts
  src/app/review/layout.tsx
  src/app/review/page.tsx
  src/app/review/step1/Step1.tsx
  src/app/review/step1/_components/achievement/Achievement.tsx
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/step1/_components/paging-button/PagingButton.tsx
  src/app/review/step1/_components/todo/ListItem.tsx
  src/app/review/step1/_components/todo/NextTodoInput.tsx
  src/app/review/step1/_components/todo/Todo.tsx
  src/app/review/step2/Step2.tsx
  src/app/review/step2/_components/paging-button/PagingButton.tsx
  src/app/review/step3/Step3.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/app/review/stores.ts
  src/app/review/types.ts
  src/app/review/utils.ts
  src/components/modal/Alert.tsx
  src/components/toast/ToastContainer.tsx
  src/utils/number.ts
Labels: 회고

#73 [FIX] auth 관련 QA 반영
  src/apis/auth/constants.ts
  src/app/(with-navigation)/dashboards/_components/SignUpSuccessModal.tsx
  src/app/(with-navigation)/dashboards/page.tsx
  src/app/auth/email-verification/components.tsx
  src/app/auth/login/components.tsx
  src/app/auth/password/components.tsx
  src/assets/images/sign-up-success.png
  src/components/inputs/number/NumberInput.tsx
  src/hooks/useTimer.tsx
  src/hooks/useUser.tsx
Labels: 인증/인가

#74 [FIX] QA 1.0 일부 반영
  src/app/(with-navigation)/dashboards/_components/MemoList.tsx
  src/app/(with-navigation)/dashboards/_components/TodoList.tsx
  src/app/(with-navigation)/dashboards/_components/WeekNavigator.tsx
  src/app/(with-navigation)/history/_components/Category.tsx
  src/app/(with-navigation)/history/memo/_components/MemoHistory/EmptyMemoHistory.tsx
  src/app/(with-navigation)/history/memo/_components/MemoHistory/MemoHistory.tsx
  src/app/(with-navigation)/history/review/_components/review-history/EmptyReviewHistory.tsx
  src/app/(with-navigation)/project/_components/project-item/NoItem.tsx
  src/app/auth/layout.tsx
  src/app/auth/login/page.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewItem.tsx
  src/app/review/step1/Step1.tsx
  src/app/review/step2/Step2.tsx
  src/app/review/step3/Step3.tsx
  src/components/inputs/checkbox/CheckboxInput.tsx
  src/styles/animations.ts
Labels: 공통, 대시보드

#75 [FIX] 회고 QA 1.0 반영
  src/app/review/_components/add-button/AddButton.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewContainer.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewItem.tsx
  src/app/review/_components/tip/Tip.tsx
  src/app/review/_components/weekly-memo/WeeklyMemo.tsx
  src/app/review/step1/_components/paging-button/PagingButton.tsx
  src/app/review/step2/Step2.tsx
  src/app/review/step2/_components/paging-button/PagingButton.tsx
  src/app/review/step3/Step3.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/app/review/types.ts
  src/components/memo/Memo.tsx
  src/components/modal/text-editor/index.tsx
  src/utils/date.ts
Labels: 공통, 회고

#77 [FEAT] 유저 프로필 부분 구현
  src/apis/user/get.ts
  src/apis/user/put.ts
  src/app/(with-navigation)/dashboards/_components/TodoList.tsx
  src/components/header/Header.tsx
  src/components/modal/setting-profile/SettingAccount.tsx
  src/components/modal/setting-profile/SettingProfile.tsx
  src/components/modal/setting-profile/index.tsx
  src/hooks/useUser.tsx
  src/stores/user/userInfo.ts
Labels: 공통

#80 [Fix] QA 0.9.3 반영
  src/apis/auth/constants.ts
  src/apis/review/post.ts
  src/app/(with-navigation)/dashboards/page.tsx
  src/app/auth/layout.tsx
  src/app/auth/login/components.tsx
  src/app/auth/login/page.tsx
  src/app/review/_components/add-button/AddButton.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewContainer.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewItem.tsx
  src/app/review/_components/weekly-memo/WeeklyMemo.tsx
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/step1/_components/paging-button/PagingButton.tsx
  src/app/review/step1/_components/todo/ListItem.tsx
  src/app/review/step1/_components/todo/NextTodoInput.tsx
  src/app/review/step1/_components/todo/TodoList.tsx
  src/app/review/step2/_components/paging-button/PagingButton.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/app/review/stores.ts
  src/app/review/types.ts
  src/components/action-sheets/Container.tsx
  src/components/action-sheets/create-project/CreateProjectSheet.tsx
  src/components/memo/Memo.tsx
  src/components/memo/MemoBottom.tsx
  src/components/modal/text-editor/index.tsx
  src/components/text-editor/MenuBar.tsx
  src/hooks/useTodosApi.tsx
  src/utils/number.ts
Labels: 인증/인가, 공통, 프로젝트, 회고

#82 [FIX] 0.9.4 반영
  src/app/auth/login/components.tsx
  src/app/auth/login/page.tsx
  src/app/auth/reset-password/components.tsx
  src/app/auth/reset-password/page.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewContainer.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewItem.tsx
  src/app/review/page.tsx
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/stores.ts
  src/components/score-picker/ScorePicker.tsx
  src/hooks/useResetReview.tsx
  src/stores/user/emailAtom.ts
  src/utils/date.ts
Labels: 인증/인가, 회고
