Repository team-vera6/career-client, pull requests merged in 2024-07, with the labels that each got.

#35 [REFACTOR] toast container 리팩토링, eslint, prettier 설정 변경
  .eslintrc.js
  .prettierrc.js
  package.json
  pnpm-lock.yaml
  src/app/(with-navigation)/dashboard/_components/MemoList.tsx
  src/app/(with-navigation)/dashboard/page.tsx
  src/app/landing/FeatureItem.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/step1/_components/todo/Buttons.tsx
  src/components/action-sheets/Container.tsx
  src/components/header/Header.tsx
  src/components/icons/AlertIcon.tsx
  src/components/icons/ChevronUp20Icon.tsx
  src/components/icons/CloseIcon.tsx
  src/components/icons/CursorPointingIcon.tsx
  src/components/icons/DashboardIcon.tsx
  src/components/icons/EditIcon.tsx
  src/components/icons/FolderIcon.tsx
  src/components/icons/FullArrowIcon.tsx
  src/components/icons/LinkIcon.tsx
  src/components/icons/MoreIcon.tsx
  src/components/icons/PlusIcon.tsx
  src/components/icons/RefreshIcon.tsx
  src/components/icons/SheetCloseIcon.tsx
  src/components/icons/SubIcon.tsx
  src/components/icons/TextLogo.tsx
  src/components/icons/YellowFolderIcon.tsx
  src/components/icons/markdown/BoldIcon.tsx
  src/components/icons/markdown/CodeBlockIcon.tsx
  src/components/icons/markdown/Header1Icon.tsx
  src/components/icons/markdown/Header2Icon.tsx
  src/components/icons/markdown/Header3Icon.tsx
  src/components/icons/markdown/ItalicIcon.tsx
  src/components/icons/markdown/MarkdownLinkIcon.tsx
  src/components/icons/markdown/OrderedListIcon.tsx
  src/components/icons/markdown/UnderlineIcon.tsx
  src/components/icons/markdown/UnorderedListIcon.tsx
  src/components/inputs/checkbox/CheckboxInput.tsx
  src/components/inputs/input/Input.tsx
  src/components/inputs/line/LineInput.tsx
  src/components/inputs/number/NumberInput.tsx
  src/components/inputs/password/PasswordInput.tsx
  src/components/inputs/textarea/Textarea.tsx
  src/components/modal/Alert.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/setting-profile/SettingAccount.tsx
  src/components/modal/setting-profile/index.tsx
  src/components/modal/text-editor/index.tsx
  src/components/navigation-bar/LeftNavigationBar.tsx
  src/components/progress-chip/ProgressChip.tsx
  src/components/score-picker/ScorePicker.tsx
  src/components/text-editor/MenuBar.tsx
  src/components/toast/ToastContainer.tsx
  src/components/toggle-switch/ToggleSwitch.tsx
  src/hooks/useToast.tsx
Labels: 공통

#36 [FEAT] 회고 step2, step3 (하이라이트 / 로우라이트) 페이지 마크업
  src/app/review/_components/add-button/AddButton.tsx
  src/app/review/_components/current-review/CurrentReview.tsx
  src/app/review/_components/current-review/CurrentReviewContainer.tsx
  src/app/review/_components/current-review/CurrentReviewItem.tsx
  src/app/review/_components/delete-button/DeleteButton.tsx
  src/app/review/_components/last-review/LastReview.tsx
  src/app/review/_components/last-review/LastReviewContainer.tsx
  src/app/review/_components/last-review/LastReviewItem.tsx
  src/app/review/_components/tip/Tip.tsx
  src/app/review/layout.tsx
  src/app/review/step1/page.tsx
  src/app/review/step2/page.tsx
  src/app/review/step3/page.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/icons/LinkIcon.tsx
  src/components/icons/LowlightCircleIcon.tsx
  src/components/inputs/textarea/Textarea.tsx
  src/components/progress-chip/ProgressChip.tsx
Labels: 회고

#37 [FEAT] ProgressDots 개발, 토스트메세지 스토리북 추가
  src/components/progress-dots/ProgressDots.stories.tsx
  src/components/progress-dots/ProgressDots.tsx
  src/components/toast/Toast.stories.tsx
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
Labels: 공통

#39 [FEAT] 회고 페이지 로직 및 더미데이터 추가, 기타 공통 컴포넌트 수정
  src/app/review/_components/add-button/AddButton.tsx
  src/app/review/_components/current-review/CurrentReview.tsx
  src/app/review/_components/current-review/CurrentReviewContainer.tsx
  src/app/review/_components/current-review/CurrentReviewItem.tsx
  src/app/review/_components/delete-button/DeleteButton.tsx
  src/app/review/_components/last-review/LastReview.tsx
  src/app/review/_components/last-review/LastReviewContainer.tsx
  src/app/review/_components/last-review/LastReviewItem.tsx
  src/app/review/_components/project-dropdown/ProjectDropdown.tsx
  src/app/review/_components/tip/Tip.tsx
  src/app/review/_components/week-info/ActivePage.tsx
  src/app/review/_components/week-info/WeekInfo.tsx
  src/app/review/_components/weekly-memo/WeeklyMemo.tsx
  src/app/review/dummy.ts
  src/app/review/step1/_components/achievement/Score.tsx
  src/app/review/step1/_components/paging-button/PagingButton.tsx
  src/app/review/step1/_components/todo/Buttons.tsx
  src/app/review/step1/_components/todo/ListItem.tsx
  src/app/review/step1/_components/todo/TodoList.tsx
  src/app/review/step1/page.tsx
  src/app/review/step2/_components/paging-button/PagingButton.tsx
  src/app/review/step2/page.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/app/review/step3/page.tsx
  src/app/review/stores.ts
  src/app/review/types.ts
  src/app/review/utils.ts
  src/components/dropdown/Dropdown.tsx
  src/components/inputs/textarea/Textarea.tsx
  src/components/memo/Memo.tsx
  src/components/memo/MemoBottom.tsx
  src/components/modal/Alert.tsx
  src/styles/colors.ts
Labels: 공통, 회고

#38 [FEAT] 대시보드 로직 연동 및 컴포넌트 분리
  src/app/(with-navigation)/dashboard/_components/MemoList.tsx
  src/app/(with-navigation)/dashboard/_components/Metrics.tsx
  src/app/(with-navigation)/dashboard/_components/TodoList.tsx
  src/app/(with-navigation)/dashboard/_components/WeekNavigator.tsx
  src/app/(with-navigation)/dashboard/page.tsx
  src/components/modal/text-editor/index.tsx
  src/types/todo.ts
  src/utils/format.ts
Labels: 대시보드

#40 [FEAT] 회고 페이지 추가 구현
  src/app/review/_components/current-review/CurrentReviewItem.tsx
  src/app/review/step2/_components/paging-button/PagingButton.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/header/Header.tsx
Labels: 공통, 회고

#41 [FEAT] : 데모데이용 임시 모달 상세 개발
  src/app/review/layout.tsx
  src/components/memo/Memo.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/demo-memo/DemoMemo.tsx
Labels: 회고

#43 [FEAT] 준비중인 서비스입니다 모달 추가
  src/app/review/_components/project-dropdown/ProjectDropdown.tsx
  src/components/modal/demo-alert/DemoAlert.tsx
  src/components/navigation-bar/LeftNavigationBar.tsx
Labels: 공통

#42 [FEAT] 대시보드 페이지 더미데이터 생성
  next.config.mjs
  src/app/(with-navigation)/dashboard/_components/MemoList.tsx
  src/app/(with-navigation)/dashboard/_components/TodoList.tsx
  src/app/(with-navigation)/dashboard/page.tsx
  src/components/inputs/checkbox/CheckboxInput.tsx
Labels: 대시보드

#44 [FIX] 데모데이 수정사항 반영
  src/app/review/_components/current-review/CurrentReviewItem.tsx
  src/components/memo/Memo.tsx
  src/components/memo/MemoBottom.tsx
  src/components/modal/text-editor/index.tsx
Labels: 회고
