Repository team-vera6/career-client, pull requests merged in 2024-08, with the labels that each got.

#45 [FEAT] 히스토리 마크업
  next.config.mjs
  src/app/(with-navigation)/history/_components/Category.tsx
  src/app/(with-navigation)/history/_components/review/Score.tsx
  src/app/(with-navigation)/history/memo/page.tsx
  src/app/(with-navigation)/history/review/_components/HistoryReview/EmptyHistoryReview.tsx
  src/app/(with-navigation)/history/review/_components/HistoryReview/HistoryReview.tsx
  src/app/(with-navigation)/history/review/_components/HistoryReview/ReviewItem.tsx
  src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetail.tsx
  src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetailSheet.tsx
  src/app/(with-navigation)/history/review/page.tsx
  src/app/(with-navigation)/report/page.tsx
  src/app/review/_components/current-week-review/CurrentWeekReview.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewContainer.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewItem.tsx
  src/app/review/_components/last-review/LastReviewItem.tsx
  src/app/review/_components/last-week-review/LastWeekReview.tsx
  src/app/review/_components/last-week-review/LastWeekReviewContainer.tsx
  src/app/review/_components/last-week-review/LastWeekReviewItem.tsx
  src/app/review/_components/project-dropdown/ProjectDropdown.tsx
  src/app/review/dummy.ts
  src/app/review/step2/page.tsx
  src/app/review/step3/page.tsx
  src/app/review/stores.ts
  src/app/review/types.ts
  src/assets/images/review-empty.png
  src/components/dropdown/Dropdown.tsx
  src/components/inputs/deletable-input/DeletableInput.stories.tsx
  src/components/inputs/deletable-input/DeletableInput.tsx
  src/components/inputs/textarea/Textarea.tsx
  src/components/modal/Alert.tsx
  src/components/navigation-bar/LeftNavigationBar.tsx
  src/components/progress-dots/ProgressDots.tsx
  src/types/attributes.ts
Labels: 히스토리

#47 [FEAT] history/memo 마크업
  src/app/(with-navigation)/history/_components/Category.tsx
  src/app/(with-navigation)/history/memo/_components/MemoHistory/EmptyMemoHistory.tsx
  src/app/(with-navigation)/history/memo/_components/MemoHistory/MemoHistory.tsx
  src/app/(with-navigation)/history/memo/_components/MemoHistory/dummy.ts
  src/app/(with-navigation)/history/memo/page.tsx
  src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetailSheet.tsx
  src/app/(with-navigation)/history/review/_components/review-history/EmptyReviewHistory.tsx
  src/app/(with-navigation)/history/review/_components/review-history/ReviewHistory.tsx
  src/app/(with-navigation)/history/review/_components/review-history/ReviewItem.tsx
  src/app/(with-navigation)/history/review/page.tsx
  src/app/review/_components/project-dropdown/ProjectDropdown.tsx
  src/app/review/types.ts
  src/components/memo/Memo.tsx
  src/components/modal/demo-alert/DemoAlert.tsx
  src/components/modal/demo-memo/DemoMemo.tsx
Labels: 히스토리

#48 [FEAT] markup-v1을 위한 추가 리팩토링
  src/app/review/_components/project-dropdown/ProjectDropdown.tsx
  src/app/review/layout.tsx
  src/components/action-sheets/edit-project/EditProjectSheet.tsx
  src/components/memo/Memo.tsx
  src/components/modal/text-editor/index.tsx
Labels: 공통, 회고

#49 [FEAT] 랜딩 페이지 제작
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/app/landing/FeatureItem.tsx
  src/app/landing/VerticalDivider.tsx
  src/app/landing/_components/Footer.tsx
  src/app/landing/_components/Header.tsx
  src/app/landing/_components/Images.tsx
  src/app/landing/_components/Title.tsx
  src/app/landing/page.tsx
  src/assets/images/friday.png
  src/assets/images/landing/landing-1.webp
  src/assets/images/landing/landing-2.webp
  src/assets/images/landing/landing-3.webp
  src/assets/logos/LogoGray.png
  src/components/icons/FridayIcon.tsx
  tailwind.config.ts
Labels: 공통

#50 [FEAT] api index 작성, proxy 설정, 로그인 개발
  next.config.mjs
  src/apis/auth/login.ts
  src/apis/index.ts
  src/app/(with-navigation)/layout.tsx
  src/app/auth/login/components.tsx
  src/app/layout.tsx
  src/hooks/useUser.tsx
  src/stores/user/accessTokenAtom.ts
  src/types/apis.ts
Labels: 인증/인가, 공통

#51 [FEAT] useUser return 방식 변경
  src/app/auth/login/components.tsx
  src/hooks/useUser.tsx
Labels: 인증/인가

#52 [FEAT] 대시보드 페이지 api 연동
  next.config.mjs
  src/apis/get-dashboard/get.ts
  src/apis/index.ts
  src/apis/memo/get.ts
  src/app/(with-navigation)/dashboard-page/_components/MemoList.tsx
  src/app/(with-navigation)/dashboard-page/_components/Metrics.tsx
  src/app/(with-navigation)/dashboard-page/_components/TodoList.tsx
  src/app/(with-navigation)/dashboard-page/_components/WeekNavigator.tsx
  src/app/(with-navigation)/dashboard-page/page.tsx
  src/app/(with-navigation)/dashboard/page.tsx
  src/app/landing/page.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/components/header/Header.tsx
  src/components/navigation-bar/LeftNavigationBar.tsx
  src/types/currentWeek.ts
  src/utils/date.ts
Labels: 대시보드

#53 [FEAT] 회원가입 api 연동
  src/apis/auth/constants.ts
  src/apis/auth/login.ts
  src/apis/auth/post.ts
  src/apis/index.ts
  src/app/auth/email-verification/components.tsx
  src/app/auth/email-verification/page.tsx
  src/app/auth/email/components.tsx
  src/app/auth/email/page.tsx
  src/app/auth/enter-email/components.tsx
  src/app/auth/enter-email/page.tsx
  src/app/auth/login/components.tsx
  src/app/auth/password/components.tsx
  src/app/auth/sign-up/components.tsx
  src/components/inputs/number/NumberInput.tsx
  src/components/inputs/password/PasswordInput.tsx
  src/hooks/useTimer.tsx
  src/hooks/useUser.tsx
  src/stores/user/emailCodeAtom.ts
  src/stores/user/signUpAtom.ts
  src/stores/user/tokenAtom.ts
  src/utils/parse.ts
Labels: 인증/인가

#54 [FEAT] 프로젝트 페이지 api 연동
  src/apis/get-dashboard/get.ts
  src/apis/memo/get.ts
  src/apis/projects/get.ts
  src/apis/projects/post.ts
  src/apis/projects/put.ts
  src/app/(with-navigation)/project/_components/project-item/ProjectItem.tsx
  src/app/(with-navigation)/project/page.tsx
  src/components/action-sheets/create-project/CreateProjectSheet.tsx
  src/components/action-sheets/edit-project/EditProjectSheet.tsx
  src/components/action-sheets/project-detail/ProjectDetailSheet.tsx
  src/components/action-sheets/project-detail/_components/RelatedReview.tsx
  src/components/header/Header.tsx
  src/types/highlight.ts
  src/types/project.ts
  src/types/sort.ts
  src/utils/date.ts
Labels: 프로젝트

#57 [FIX] 페이지 이름 변경
  next.config.mjs
  src/apis/projects/post.ts
  src/app/(with-navigation)/dashboards/_components/MemoList.tsx
  src/app/(with-navigation)/dashboards/_components/Metrics.tsx
  src/app/(with-navigation)/dashboards/_components/TodoList.tsx
  src/app/(with-navigation)/dashboards/_components/WeekNavigator.tsx
  src/app/(with-navigation)/dashboards/page.tsx
  src/app/landing/page.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/components/header/Header.tsx
  src/components/navigation-bar/LeftNavigationBar.tsx
Labels: 공통
