Repository team-vera6/career-client, pull requests merged in 2024-10, with the labels that each got.

#84 [FIX] QA 0.9.5 반영
  src/app/review/_components/current-week-review/CurrentWeekReviewItem.tsx
  src/app/review/page.tsx
  src/app/review/stores.ts
  src/components/dropdown/Dropdown.tsx
  src/hooks/useResetReview.tsx
  src/utils/date.ts
Labels: 회고

#85 [FIX] 마크다운 에디터 제거
  src/app/(with-navigation)/dashboards/_components/MemoList.tsx
  src/app/(with-navigation)/history/_components/Category.tsx
  src/app/review/_components/last-week-review/LastWeekReviewItem.tsx
  src/components/action-sheets/project-detail/_components/RelatedReview.tsx
  src/components/memo/Memo.tsx
  src/components/modal/memo-editor/BottomMenu.tsx
  src/components/modal/memo-editor/MemoEditor.tsx
  src/components/modal/memo-editor/TopMenu.tsx
Labels: 공통

#87 [FEAT] 다음 주 할 일이 있는 경우 다음주까지 이동 가능하도록 설정
  src/app/(with-navigation)/dashboards/_components/WeekNavigator.tsx
Labels: 대시보드

#86 [FIX] 0.9.9 반영
  src/app/review/_components/current-week-review/CurrentWeekReview.tsx
  src/app/review/_components/current-week-review/CurrentWeekReviewContainer.tsx
  src/app/review/_components/weekly-memo/WeeklyMemo.tsx
  src/app/review/layout.tsx
  src/app/review/page.tsx
  src/app/review/step3/_components/paging-button/PagingButton.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/icons/NoMemoIcon.tsx
Labels: 공통, 회고
